name: reusable-dotnet-ci

on:
  workflow_call:
    inputs:
      BRANCH:
        type: string
      SOLUTION_FILE_PATH:
        type: string
        required: true
      DOTNET_VERISON:
        type: string
        required: true
        default: '8.0.x'
      INTERNAL_NUGET_FEED:
        type: string
        required: false

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.BRANCH || github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.DOTNET_VERISON }}

    - name: Add GitHub Packages NuGet source
      if: ${{ inputs.INTERNAL_NUGET_FEED != '' }}
      run: |
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ inputs.INTERNAL_NUGET_FEED }}/index.json"

    - name: Install dependencies
      run: dotnet restore ${{ inputs.SOLUTION_FILE_PATH }}

    - name: Build
      run: dotnet build ${{ inputs.SOLUTION_FILE_PATH }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ inputs.SOLUTION_FILE_PATH }} --no-restore --blame-hang-timeout 300000 --blame